
"""
Base Manager Processes Module

This module extends the CarisBatchCommand class to provide essential management 
functionalities for server-based raster and point cloud data processing. It 
includes classes that facilitate the addition of sources to combined rasters, 
creation of new rasters from logical operations on existing data, and the merging 
of multiple point clouds into a single dataset.

Each class in this module targets specific server-based operations, making it 
possible to handle large datasets efficiently and effectively. These classes 
are crucial for the dynamic management of geospatial data within server 
environments, ensuring that data combining, joining, and transformation processes 
are optimized for large-scale projects.

The module plays a pivotal role in managing and manipulating large volumes of 
raster and point cloud data, providing robust solutions for complex data management 
scenarios in geospatial workflows.

Author: Vinicius Nogueira
Created: 15-July-2020
Last Modified: 23-November-2023

Note:
    This module is an integral part of the MK-CarisAPI.
"""

from ._carisbatch import CarisBatchCommand

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Server Add to Raster Combine
class ServerAddToRasterCombine(CarisBatchCommand):
    """
    The ServerAddToRasterCombine class adds sources to an existing combined raster using the server combine process 
    parameters stored in the CSAR metadata. This process is intended for use with CSAR raster surfaces generated by a 
    server combine process, along with additional raster surfaces, point clouds, and/or variable resolution surfaces.

    Attributes:
        _command (str): The command associated with the 'Server Add to Raster Combine' process.
        _option_key (str): Key to identify specific settings for the process, set to None as it's not required.
        _common_settings (dict): Dictionary containing the common settings for the process.
    """

    _command = 'ServerAddToRasterCombine'
    _option_key = None

    _common_settings = {
        "database_name": None,
        "login": None
    }

    class _ServerAddToRasterCombineSettings:
        """
        Nested class for ServerAddToRasterCombine settings.
        """
        default_settings = {}

    _option_registry = {
        'SERVERADDTORASTERCOMBINE': _ServerAddToRasterCombineSettings
    }


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Server Combine to Raster
class ServerCombineToRaster(CarisBatchCommand):
    """
    The ServerCombineToRaster class creates a new raster by computing values in each raster cell using a logical operation 
    executed over the points within each raster cell. This process is used for combining overlapping coverages or regenerating 
    a coverage with different settings.

    Attributes:
        _command (str): The command associated with the 'Server Combine to Raster' process.
        _option_key (str): Key to identify specific settings for the process, set to None as it's not required.
        _common_settings (dict): Dictionary containing the common settings for the process.
    """

    _command = 'ServerCombineToRaster'
    _option_key = None

    _common_settings = {
        "database_name": None,
        "login": None,
        "recompute_stats": None,
        "rule_file": None,
        "override_ambiguity": None,
        "confine_metadata_rules": None,
        "use_cell_centres": None,
        "contributor_attribute": None,
        "resolution": None,
        "anchor": None,
        "extent": None,
        "primary_band": None,
        "map_band": None,
        "output_crs": None,
        "output_vertical_crs": None,
        "comments": None
    }

    class _ServerCombineToRasterSettings:
        """
        Nested class for ServerCombineToRaster settings.
        """
        default_settings = {}

    _option_registry = {
        'SERVERCOMBINETORASTER': _ServerCombineToRasterSettings
    }


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Server Join Points
class ServerJoinPoints(CarisBatchCommand):
    """
    The ServerJoinPoints class creates a new point cloud from the points in the inputs.

    Attributes:
        _command (str): The command associated with the 'Server Join Points' process.
        _option_key (str): Key to identify specific settings for the process, set to None as it's not required.
        _common_settings (dict): Dictionary containing the common settings for the process.
    """

    _command = 'ServerJoinPoints'
    _option_key = None

    _common_settings = {
        "database_name": None,
        "login": None,
        "primary_band": None,
        "contributor_attribute": None,
        "output_crs": None,
        "output_vertical_crs": None,
        "extent": None,
        "comments": None
    }

    class _ServerJoinPointsSettings:
        """
        Nested class for ServerJoinPoints settings.
        """
        default_settings = {}

    _option_registry = {
        'SERVERJOINPOINTS': _ServerJoinPointsSettings
    }
